name: sunion

dependencies:
  - IPython=5.3.0
  - python=3.6.1
  - numpy=1.11.2
  - pandas=0.20.1
  - matplotlib=2.0.2
  - seaborn=0.7.1
  - scipy=0.18.1
  - pip:
    - watermark==1.5.0
    - nltk==3.2.4
    - sklearn